# ==============================================================================
# Azure DevOps CI Pipeline
# ==============================================================================

trigger:
  - none

variables:
  TerraformVersion: "1.12.1"
  TerraformWorkingDirectory: "$(Build.SourcesDirectory)/examples/app_with_storage/infrastructure"

pool:
  name: 'Sample'

stages:
  # ----------------------------------------------------------------------------
  # ✅ Validate Terraform Code
  # ----------------------------------------------------------------------------
  - stage: Validate
    displayName: Validation Terraform
    jobs:
      - job: validate
        displayName: Validate Terraform
        steps:
          - checkout: self

          - task: TerraformInstaller@1
            displayName: 'Install Terraform'
            inputs:
              terraformVersion: $(TerraformVersion)

          - task: TerraformTask@5
            displayName: 'Terraform Format Check'
            inputs:
              provider: 'azurerm'
              command: 'custom'
              customCommand: 'fmt'
              commandOptions: '-check -recursive'
              workingDirectory: $(TerraformWorkingDirectory)
              environmentServiceNameAzureRM: 'development'
            
          - task: TerraformTask@5
            displayName: 'Terraform Init'
            inputs:
              provider: 'azurerm'
              command: 'custom'
              customCommand: 'init'
              commandOptions: '-backend=false'
              workingDirectory: $(TerraformWorkingDirectory)
              environmentServiceNameAzureRM: 'development'
            
          - task: TerraformTask@5
            displayName: 'Terraform Validate'
            inputs:
              provider: 'azurerm'
              command: 'validate'
              workingDirectory: $(TerraformWorkingDirectory)
              environmentServiceNameAzureRM: 'development'

  # ----------------------------------------------------------------------------
  # ✅ Validate Dev Plan
  # ----------------------------------------------------------------------------
  - stage: Plan_Dev
    displayName: "🏗️ Plan"
    dependsOn: Validate
    variables:
      - group: 'development'
    jobs:
      - template: templates/plan-template.yml
        parameters:
          AzureRmServiceConnection: 'development'
          Environment: 'development'
          RootModulePath: $(TerraformWorkingDirectory)
          
  # ----------------------------------------------------------------------------
  # ✅ Validate Production Plan
  # ----------------------------------------------------------------------------
  - stage: Plan_Prod
    displayName: "🏗️ Plan"
    dependsOn: Validate
    variables:
      - group: 'production'
    jobs:
      - template: templates/plan-template.yml
        parameters:
          AzureRmServiceConnection: 'production'
          Environment: 'production'
          RootModulePath: $(TerraformWorkingDirectory)
          